version: '3.8'
services:
  db:
    image: mysql
    container_name: erp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'erp_p'
      MYSQL_DATABASE: 'erp_p'
      MYSQL_USER: 'erp_p'
      MYSQL_PASSWORD: 'erp_p'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - erp
  redis:
    container_name: erp_redis
    image: redis
    hostname: redis
    ports:
     - 6377:6379
    volumes:
      - redisdata:/data
    networks:
      - erp
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

networks:
  erp:
volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local
