version: '3.8'
services:
  db:
    image: mysql:8.0.40
    container_name: atlas_mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1q2w3E*'
      MYSQL_DATABASE: 'atlas_db'
      MYSQL_USER: 'atlas_p'
      MYSQL_PASSWORD: '1q2w3E*'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - atlas
  redis:
    container_name: atlas_redis
    image: redis
    hostname: redis
    ports:
     - 6380:6380
    volumes:
      - redisdata:/data
    networks:
      - atlas
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

networks:
  atlas:
volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local