version: '3.8'
services:
  db:
    image: mysql
    container_name: usv_schedulling_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'erp_p'
      MYSQL_DATABASE: 'erp_p'
      MYSQL_USER: 'erp_p'
      MYSQL_PASSWORD: 'erp_p'
    volumes:
      - usv_schedulling_mysqldata:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - usv_schedulling_network

  redis:
    image: redis
    container_name: usv_schedulling_redis
    restart: always
    hostname: redis
    ports:
      - 6377:6379
    volumes:
      - usv_schedulling_redisdata:/data
    networks:
      - usv_schedulling_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

networks:
  usv_schedulling_network:

volumes:
  usv_schedulling_mysqldata:
    driver: local
  usv_schedulling_redisdata:
    driver: local
